### ISSUE TITLE
Please provide GitHub details at the Google Play listing

### ISSUE THREAD

**Issue by raindropsfromsky** [farshed/SoundSpice-mobile#2]
The [Google Play listing of SoundSpice](https://play.google.com/store/apps/details?id=com.vynilla) does not reveal that this is an **open source product**. 

It does not provide a link to the [GitHub page](https://github.com/farshed/SoundSpice-mobile).

It says that if there are any bugs or suggestions, they should be sent to a personal email ID, rather than to the [GitHub issues](https://github.com/farshed/SoundSpice-mobile/issue).

Kindly correct these details.

**Comment by farshed** [comment]
@raindropsfromsky thank you for pointing that out. I've updated the listing and the changes should be available in a couple days. I've added a pointer to the GitHub issues page but also kept the email part for now because not everyone has a GitHub account. A temporary fix till we find a better solution. Any ideas?

**Comment by raindropsfromsky** [comment]
No, you are right: Some people may get intimidated by the idea of creating an account just for the sake of registering one complaint. Sending an email is a trivial task in comparison.

Thanks for the rapid response!
